log_level = "warn"
outputs = "All"
position = "Top"

[appearance]
font_name = "Unispace"
scale_factor = 1.25
style = "Islands"
opacity = 1
background_color = "#E53B44"
primary_color = "#686868"
secondary_color = "#282828"
text_color = "#000000"
workspace_colors = ["#C0C0C0", "#C0C0C0"]

[workspaces]
visibility_mode = "MonitorSpecific"

[modules]
left = ["Workspaces"]
center = ["SystemInfo"]
right = ["Clock", "Tray", "Settings"]
